inputSequence {
    header
}
subtypeText
alignedGeneSequences {
    firstAA
    lastAA
    gene { name }
    mutations {
        consensus
        position
        AAs
        triplet
        text
        isInsertion
        isDeletion
        isApobecDRM
    }
    alignedNAs
    alignedAAs
}
